import { defineIndustry, qa } from "./factory";
import type { CepIndustryPreset, ColorPalette } from "./types";

function c(
  primary: string,
  primaryEnd: string,
  header: string,
  background: string,
  text: string,
): ColorPalette {
  return {
    primary,
    primaryEnd,
    header,
    background,
    text,
    accent: "#f59e0b",
    success: "#16a34a",
    warning: "#d97706",
    surface: "#ffffff",
    darkBackground: "#0f172a",
    darkText: "#f8fafc",
    darkHeader: header,
  };
}

export const CREATIVE_PRESETS: CepIndustryPreset[] = [
  defineIndustry({
    id: "logo-design",
    category: "creative",
    industryName: "Logo Design Agency",
    catalogBlurb: "Logo briefs, packages, and portfolio-led sales.",
    designPersonality: "Craft-obsessed · iconic",
    colors: c("#6d28d9", "#a78bfa", "#5b21b6", "#faf5ff", "#2e1065"),
    assistantName: "Alex",
    assistantRole: "Your Logo Design Assistant",
    greeting: "Hi! Need a new logo or a redesign? Pick an option below and I’ll guide you.",
    matchKeywords: ["logo design", "logo designer", "logotype", "brand mark"],
    primaryCta: { label: "I need a New Logo", action: "brief" },
    secondaryCta: { label: "See Portfolio", action: "portfolio" },
    bubbleCta: "Hi! Need a logo?",
    footer: "Custom concepts — no clip-art logos.",
    businessGoal: "Increase qualified logo briefs",
    conversionGoal: "Logo brief or discovery call",
    aiPrompt: "Qualify logo projects and capture briefs. No fake portfolio claims.",
    salesStrategy: "New vs redesign → style → package → brief.",
    popularServices: ["Logo suite", "Brand mark", "Refresh"],
    quickActions: qa([
      ["new", "I need a New Logo", "pen-tool"],
      ["redesign", "Redesign My Logo", "sparkles"],
      ["pricing", "View Pricing", "layers"],
      ["portfolio", "See Our Portfolio", "image"],
      ["branding", "Branding Package", "briefcase"],
      ["call", "Book a Call", "phone", "start_form"],
      ["process", "Our Process", "git-branch"],
      ["human", "Talk to a Designer", "headphones", "transfer_agent"],
    ]),
  }),
  defineIndustry({
    id: "branding-agency",
    category: "creative",
    industryName: "Brand Identity Agency",
    catalogBlurb: "Full identity systems — strategy and visual language.",
    designPersonality: "Strategic · premium · systems thinking",
    colors: c("#be123c", "#fb7185", "#9f1239", "#fff1f2", "#4c0519"),
    assistantName: "Brand Strategist",
    assistantRole: "Brand identity consultant",
    greeting: "Building or refreshing a brand? I can walk you through identity packages and book a strategy session.",
    matchKeywords: ["brand identity", "branding agency", "brand strategy", "rebrand"],
    primaryCta: { label: "Book Strategy Session", action: "call" },
    secondaryCta: { label: "Identity Packages", action: "pricing" },
    bubbleCta: "Build your brand",
    footer: "Strategy-led branding · custom proposals for complex rebrands",
    businessGoal: "Win multi-deliverable identity retainers",
    conversionGoal: "Strategy session booked",
    aiPrompt: "Qualify identity projects. Emphasize systems, not just logos.",
    salesStrategy: "Startup vs rebrand → stakeholders → package.",
    popularServices: ["Brand strategy", "Visual identity", "Voice guidelines"],
  }),
  defineIndustry({
    id: "business-card-design",
    category: "creative",
    industryName: "Business Card Design",
    catalogBlurb: "Fast card design with print-ready delivery.",
    designPersonality: "Crisp · tactile · print-aware",
    colors: c("#1e3a8a", "#3b82f6", "#1e3a8a", "#eff6ff", "#1e3a8a"),
    assistantName: "Card Studio",
    assistantRole: "Business card design assistant",
    greeting: "Need business cards that feel premium in-hand? I can help with design packages and print-ready files.",
    matchKeywords: ["business card", "visiting card", "name card"],
    primaryCta: { label: "Order Card Design", action: "quote" },
    secondaryCta: { label: "See Styles", action: "portfolio" },
    bubbleCta: "Design cards",
    footer: "Print-ready CMYK files available",
    businessGoal: "High-volume card projects with brand-kit upsells",
    conversionGoal: "Paid card design order",
    aiPrompt: "Assist business card design orders and finishes.",
    salesStrategy: "Quantity/finish → style → package → brand kit upsell.",
    popularServices: ["Standard cards", "Foil / specialty", "Brand kit"],
  }),
  defineIndustry({
    id: "graphic-design-studio",
    category: "creative",
    industryName: "Graphic Design Studio",
    catalogBlurb: "Campaign, social, and print design coordination.",
    designPersonality: "Versatile · visual · campaign-ready",
    colors: c("#7c3aed", "#c084fc", "#6d28d9", "#faf5ff", "#3b0764"),
    assistantName: "Studio Desk",
    assistantRole: "Graphic design project coordinator",
    greeting: "From social kits to print campaigns — tell me what you need designed.",
    matchKeywords: ["graphic design", "design studio", "flyer", "social media graphics"],
    primaryCta: { label: "Start Design Brief", action: "brief" },
    secondaryCta: { label: "View Studio Work", action: "portfolio" },
    bubbleCta: "Need design?",
    footer: "Custom creative · licensed assets only",
    businessGoal: "Increase multi-asset project volume",
    conversionGoal: "Brief submitted or call booked",
    aiPrompt: "Coordinate graphic design inquiries across formats.",
    salesStrategy: "Asset type → volume → deadline → package.",
    popularServices: ["Social kits", "Print", "Campaign creative"],
  }),
  defineIndustry({
    id: "print-design",
    category: "creative",
    industryName: "Print Design Studio",
    catalogBlurb: "Brochures, collateral, and print production design.",
    designPersonality: "Production-smart · detail-obsessed",
    colors: c("#0f766e", "#14b8a6", "#115e59", "#f0fdfa", "#134e4a"),
    assistantName: "Print Desk",
    assistantRole: "Print design specialist",
    greeting: "Need brochures, flyers, or print collateral? I can help scope files and turnaround.",
    matchKeywords: ["print design", "brochure design", "flyer design", "print collateral"],
    primaryCta: { label: "Get Print Quote", action: "quote" },
    secondaryCta: { label: "See Print Work", action: "portfolio" },
    bubbleCta: "Print design help",
    footer: "Bleed, CMYK, and finish specs included",
    businessGoal: "Win print design + production jobs",
    conversionGoal: "Print quote request",
    aiPrompt: "Qualify print design projects and specs.",
    salesStrategy: "Piece type → quantity → finish → quote.",
    popularServices: ["Brochures", "Posters", "Leave-behinds"],
  }),
  defineIndustry({
    id: "packaging-design",
    category: "creative",
    industryName: "Packaging Design",
    catalogBlurb: "Product packaging and label systems.",
    designPersonality: "Tactile · retail-ready · brand-true",
    colors: c("#c2410c", "#fb923c", "#9a3412", "#fff7ed", "#7c2d12"),
    assistantName: "Pack Studio",
    assistantRole: "Packaging design consultant",
    greeting: "Launching a product? I can help with packaging concepts, dielines, and production-ready art.",
    matchKeywords: ["packaging design", "label design", "product packaging", "dieline"],
    primaryCta: { label: "Start Packaging Brief", action: "brief" },
    secondaryCta: { label: "Packaging Work", action: "portfolio" },
    bubbleCta: "Design packaging",
    footer: "Production files prepared for your printer",
    businessGoal: "Win packaging system projects",
    conversionGoal: "Packaging brief submitted",
    aiPrompt: "Qualify packaging design projects and manufacturing constraints.",
    salesStrategy: "SKU count → retail channel → brief → quote.",
    popularServices: ["Labels", "Boxes", "Shipper design"],
  }),
  defineIndustry({
    id: "creative-design-agency",
    category: "creative",
    industryName: "Creative Design Agency",
    catalogBlurb: "Full-service creative for brands and campaigns.",
    designPersonality: "Bold · collaborative · idea-led",
    colors: c("#db2777", "#f472b6", "#9d174d", "#fdf2f8", "#831843"),
    assistantName: "Creative Desk",
    assistantRole: "Creative agency assistant",
    greeting: "Need a creative partner for campaigns or brand work? I can map packages and book a chemistry call.",
    matchKeywords: ["creative agency", "creative studio", "campaign creative", "art direction"],
    primaryCta: { label: "Book Chemistry Call", action: "call" },
    secondaryCta: { label: "Capabilities", action: "services" },
    bubbleCta: "Let's create",
    footer: "Custom retainers for ongoing creative",
    businessGoal: "Close creative retainers",
    conversionGoal: "Chemistry call booked",
    aiPrompt: "Qualify creative agency opportunities and book calls.",
    salesStrategy: "Campaign vs retainer → budget → call.",
    popularServices: ["Campaigns", "Art direction", "Content creative"],
  }),
  defineIndustry({
    id: "marketing-collateral",
    category: "creative",
    industryName: "Marketing Collateral Design",
    catalogBlurb: "Decks, one-pagers, and sales enablement design.",
    designPersonality: "Sales-enablement · crisp · conversion-aware",
    colors: c("#1d4ed8", "#60a5fa", "#1e40af", "#eff6ff", "#1e3a8a"),
    assistantName: "Collateral Desk",
    assistantRole: "Marketing collateral designer assistant",
    greeting: "Need pitch decks, one-pagers, or sales sheets? I can help scope and quote quickly.",
    matchKeywords: ["marketing collateral", "pitch deck", "one-pager", "sales sheet", "leave behind"],
    primaryCta: { label: "Quote Collateral", action: "quote" },
    secondaryCta: { label: "See Examples", action: "portfolio" },
    bubbleCta: "Need sales assets?",
    footer: "Brand-consistent sales enablement design",
    businessGoal: "Increase collateral project volume",
    conversionGoal: "Collateral quote submitted",
    aiPrompt: "Qualify marketing collateral design requests.",
    salesStrategy: "Asset list → brand assets ready? → quote.",
    popularServices: ["Pitch decks", "One-pagers", "Case study layouts"],
  }),
];
