import { defineIndustry, qa } from "./factory";
import type { CepIndustryPreset, ColorPalette } from "./types";

function c(
  primary: string,
  primaryEnd: string,
  header: string,
  background: string,
  text: string,
): ColorPalette {
  return {
    primary,
    primaryEnd,
    header,
    background,
    text,
    accent: "#f59e0b",
    success: "#16a34a",
    warning: "#d97706",
    surface: "#ffffff",
    darkBackground: "#0f172a",
    darkText: "#f8fafc",
    darkHeader: header,
  };
}

export const DENTAL_PRESETS: CepIndustryPreset[] = [
  defineIndustry({
    id: "cosmetic-dentistry",
    category: "dental",
    industryName: "Cosmetic Dentistry",
    catalogBlurb: "Smile makeovers, veneers, and whitening consults.",
    designPersonality: "Polished · aesthetic · confidence-building",
    colors: c("#0891b2", "#22d3ee", "#155e75", "#ecfeff", "#164e63"),
    assistantName: "Smile Studio",
    assistantRole: "Cosmetic dentistry consultant",
    greeting: "Dreaming of a brighter smile? I can help with whitening, veneers, and smile consults.",
    matchKeywords: ["cosmetic dentistry", "veneers", "smile makeover", "teeth whitening"],
    primaryCta: { label: "Smile Consult", action: "consult" },
    secondaryCta: { label: "Before / After", action: "portfolio" },
    bubbleCta: "Upgrade your smile",
    footer: "Cosmetic results vary — consult required.",
    businessGoal: "Book high-value cosmetic consults",
    conversionGoal: "Smile consult scheduled",
    aiPrompt: "Help cosmetic dentistry consults. No outcome guarantees.",
    salesStrategy: "Goal → photos → consult → financing FAQ.",
    popularServices: ["Veneers", "Whitening", "Smile design"],
  }),
  defineIndustry({
    id: "dental-implant",
    category: "dental",
    industryName: "Dental Implant Center",
    catalogBlurb: "Implant consults, All-on-X interest, and financing paths.",
    designPersonality: "Expert · restorative · high-trust",
    colors: c("#0f766e", "#2dd4bf", "#115e59", "#f0fdfa", "#134e4a"),
    assistantName: "Implant Advisor",
    assistantRole: "Dental implant specialist assistant",
    greeting: "Missing teeth or considering implants? I can help start a free implant consult.",
    matchKeywords: ["dental implant", "implants", "all-on-4", "all on 4", "tooth replacement"],
    primaryCta: { label: "Free Implant Consult", action: "consult" },
    secondaryCta: { label: "Financing Options", action: "financing" },
    bubbleCta: "Ask about implants",
    footer: "Implant candidacy requires clinical evaluation.",
    businessGoal: "Increase implant consult volume",
    conversionGoal: "Implant consult booked",
    aiPrompt: "Qualify implant interest and book consults. No clinical promises.",
    salesStrategy: "Single vs full-arch → consult → financing.",
    popularServices: ["Single implant", "All-on-X", "Bone graft consult"],
  }),
  defineIndustry({
    id: "pediatric-dentistry",
    category: "dental",
    industryName: "Pediatric Dentistry",
    catalogBlurb: "Kid-friendly dental booking for parents.",
    designPersonality: "Playful · gentle · parent-trusted",
    colors: c("#2563eb", "#60a5fa", "#1d4ed8", "#eff6ff", "#1e3a8a"),
    assistantName: "Kids Smile Desk",
    assistantRole: "Pediatric dental assistant",
    greeting: "Booking for your child? I can help with checkups, first visits, and gentle care questions.",
    matchKeywords: ["pediatric dentist", "kids dentist", "children's dentistry", "child dentist"],
    primaryCta: { label: "Book Kids Visit", action: "book" },
    secondaryCta: { label: "First Visit Tips", action: "prep" },
    bubbleCta: "Kids dental care",
    footer: "Dental emergencies: call the office or ER if severe.",
    businessGoal: "Grow pediatric patient base",
    conversionGoal: "Child appointment booked",
    aiPrompt: "Help parents book pediatric dental visits. Warm and clear.",
    salesStrategy: "Child age → visit type → book → parent contact.",
    popularServices: ["Kids checkup", "Sealants", "First visit"],
  }),
  defineIndustry({
    id: "endodontics",
    category: "dental",
    industryName: "Endodontics",
    catalogBlurb: "Root canal specialty consults and referral intake.",
    designPersonality: "Precise · reassuring · specialty",
    colors: c("#4f46e5", "#818cf8", "#3730a3", "#eef2ff", "#1e1b4b"),
    assistantName: "Root Canal Desk",
    assistantRole: "Endodontic intake assistant",
    greeting: "Need a root canal specialist? I can help with referrals, consults, and what to expect.",
    matchKeywords: ["endodont", "root canal", "endodontist"],
    primaryCta: { label: "Book Endo Consult", action: "book" },
    secondaryCta: { label: "What to Expect", action: "faq" },
    bubbleCta: "Root canal help",
    footer: "Severe swelling/fever may need urgent care.",
    businessGoal: "Convert referrals to scheduled procedures",
    conversionGoal: "Endodontic consult booked",
    aiPrompt: "Assist endodontic scheduling and prep FAQs.",
    salesStrategy: "Referral status → urgency → book.",
    popularServices: ["Root canal", "Retreatment", "Apicoectomy consult"],
  }),
  defineIndustry({
    id: "oral-surgery",
    category: "dental",
    industryName: "Oral Surgery",
    catalogBlurb: "Extractions, wisdom teeth, and surgical consults.",
    designPersonality: "Clinical · clear · prep-focused",
    colors: c("#be123c", "#fb7185", "#9f1239", "#fff1f2", "#4c0519"),
    assistantName: "Oral Surgery Desk",
    assistantRole: "Oral surgery coordinator",
    greeting: "Wisdom teeth or oral surgery questions? I can help schedule a consult and share prep basics.",
    matchKeywords: ["oral surgery", "wisdom teeth", "tooth extraction", "oral surgeon"],
    primaryCta: { label: "Surgery Consult", action: "consult" },
    secondaryCta: { label: "Prep Checklist", action: "prep" },
    bubbleCta: "Oral surgery help",
    footer: "Uncontrolled bleeding or airway issues → ER.",
    businessGoal: "Book surgical consults",
    conversionGoal: "Oral surgery consult scheduled",
    aiPrompt: "Coordinate oral surgery consults and prep. No clinical advice.",
    salesStrategy: "Procedure interest → consult → anesthesia FAQ.",
    popularServices: ["Wisdom teeth", "Extractions", "Implant surgery"],
    quickActions: qa([
      ["consult", "Surgery Consult", "calendar"],
      ["wisdom", "Wisdom Teeth", "alert"],
      ["prep", "Prep Checklist", "file-text"],
      ["sedation", "Sedation Options", "heart"],
      ["insurance", "Insurance", "shield"],
      ["reviews", "Patient Reviews", "sparkles"],
      ["callback", "Call Me Back", "phone"],
      ["human", "Talk to Coordinator", "headphones", "transfer_agent"],
    ]),
  }),
];
