import { defineIndustry, qa } from "./factory";
import type { CepIndustryPreset, ColorPalette } from "./types";

function c(
  primary: string,
  primaryEnd: string,
  header: string,
  background: string,
  text: string,
  accent = "#f59e0b",
): ColorPalette {
  return {
    primary,
    primaryEnd,
    header,
    background,
    text,
    accent,
    success: "#16a34a",
    warning: "#d97706",
    surface: "#ffffff",
    darkBackground: "#0f172a",
    darkText: "#f8fafc",
    darkHeader: header,
  };
}

export const HEALTHCARE_PRESETS: CepIndustryPreset[] = [
  defineIndustry({
    id: "emergency-room",
    category: "healthcare",
    industryName: "Emergency Room (ER)",
    catalogBlurb: "Safety-first ER navigator with wait times and entrance help.",
    designPersonality: "Urgent · calm · clinical",
    colors: c("#b91c1c", "#dc2626", "#7f1d1d", "#fff7f7", "#1c1917"),
    assistantName: "ER Guide",
    assistantRole: "Emergency department navigator",
    greeting: "If this is life-threatening, call 911. I can help with wait times, entrances, and what to bring.",
    matchKeywords: ["emergency room", "er", "trauma", "emergency department"],
    primaryCta: { label: "ER Directions", action: "directions" },
    secondaryCta: { label: "Wait Times", action: "wait" },
    bubbleCta: "Need ER help?",
    footer: "For life-threatening emergencies call 911.",
    businessGoal: "Reduce confused arrivals while protecting safety",
    conversionGoal: "Correct entrance + prepared arrival",
    aiPrompt: "You are an ER navigator. Never diagnose. Escalate emergencies to 911.",
    salesStrategy: "Prioritize safety over conversion.",
    popularServices: ["Trauma", "Pediatric ER", "Stroke / cardiac pathway"],
    quickActions: qa([
      ["911", "Call 911", "phone", "open_url", "tel:911"],
      ["wait", "ER Wait Time", "clock"],
      ["directions", "ER Entrance", "map-pin"],
      ["trauma", "Trauma Signs", "alert"],
      ["kids", "Pediatric ER", "heart"],
      ["parking", "Parking", "car"],
      ["insurance", "Insurance", "shield"],
      ["human", "Nurse Line", "headphones", "transfer_agent"],
    ]),
  }),
  defineIndustry({
    id: "urgent-care",
    category: "healthcare",
    industryName: "Urgent Care Clinic",
    catalogBlurb: "Same-day care booking with symptom routing.",
    designPersonality: "Fast · friendly · clinic-ready",
    colors: c("#0f766e", "#14b8a6", "#115e59", "#f0fdfa", "#134e4a"),
    assistantName: "Care Concierge",
    assistantRole: "Urgent care intake assistant",
    greeting: "Need same-day care? I can help check fit, wait times, and save you a spot.",
    matchKeywords: ["urgent care", "walk-in clinic", "same-day care"],
    primaryCta: { label: "Save My Spot", action: "book" },
    secondaryCta: { label: "Check Symptoms", action: "symptoms" },
    bubbleCta: "Same-day care?",
    footer: "Not for emergencies — call 911 if life-threatening.",
    businessGoal: "Fill same-day capacity with right acuity",
    conversionGoal: "Booked / held visit",
    aiPrompt: "Help decide urgent care vs ER, book visits, never diagnose.",
    salesStrategy: "Qualify urgency → hold/book → insurance → arrival window.",
    popularServices: ["Minor injury", "Illness", "Labs on-site"],
  }),
  defineIndustry({
    id: "general-medical-clinic",
    category: "healthcare",
    industryName: "General Medical Clinic",
    catalogBlurb: "Primary-care style clinic with appointments and portal help.",
    designPersonality: "Warm clinical · organized",
    colors: c("#1d4ed8", "#3b82f6", "#1e3a8a", "#f8fafc", "#0f172a"),
    assistantName: "Clinic Desk",
    assistantRole: "Medical clinic assistant",
    greeting: "Hi — I can help with appointments, services, insurance questions, and directions.",
    matchKeywords: ["medical clinic", "primary care clinic", "family clinic", "outpatient clinic"],
    primaryCta: { label: "Book Visit", action: "book" },
    secondaryCta: { label: "Our Services", action: "services" },
    bubbleCta: "Need a clinic visit?",
    footer: "This chat does not provide medical diagnosis.",
    businessGoal: "Increase booked visits and reduce phone load",
    conversionGoal: "Scheduled appointment",
    aiPrompt: "Assist a medical clinic with scheduling and FAQs. No diagnosis.",
    salesStrategy: "Need → new/returning → book → insurance capture.",
    popularServices: ["Checkups", "Sick visits", "Labs"],
  }),
  defineIndustry({
    id: "hospital",
    category: "healthcare",
    industryName: "Hospital",
    catalogBlurb: "Multi-department hospital guide for visitors and patients.",
    designPersonality: "Authoritative · reassuring · campus-scale",
    colors: c("#0f172a", "#334155", "#020617", "#f8fafc", "#0f172a", "#38bdf8"),
    assistantName: "Hospital Guide",
    assistantRole: "Patient & visitor navigator",
    greeting: "Welcome — I can help with departments, visiting hours, parking, and appointments.",
    matchKeywords: ["hospital", "medical center", "health system", "inpatient"],
    primaryCta: { label: "Find Department", action: "services" },
    secondaryCta: { label: "Visitor Info", action: "hours" },
    bubbleCta: "Hospital help",
    footer: "For emergencies call 911.",
    businessGoal: "Improve wayfinding and appointment starts",
    conversionGoal: "Department routing or booked visit",
    aiPrompt: "Guide hospital visitors. Escalate emergencies. No clinical advice.",
    salesStrategy: "Route to department → appointment or visitor logistics.",
    popularServices: ["ER", "Surgery", "Maternity", "Imaging"],
  }),
  defineIndustry({
    id: "family-doctor",
    category: "healthcare",
    industryName: "Family Doctor",
    catalogBlurb: "Family practice scheduling and new-patient onboarding.",
    designPersonality: "Warm · personal · neighborhood trust",
    colors: c("#15803d", "#22c55e", "#14532d", "#f0fdf4", "#14532d"),
    assistantName: "Family Care Desk",
    assistantRole: "Family practice assistant",
    greeting: "Looking for a family doctor visit? I can help new and returning patients book.",
    matchKeywords: ["family doctor", "family medicine", "gp", "primary care physician"],
    primaryCta: { label: "Book Appointment", action: "book" },
    secondaryCta: { label: "New Patient", action: "intake" },
    bubbleCta: "Book family care",
    footer: "Not for emergencies — call 911 if urgent.",
    businessGoal: "Keep the panel booked",
    conversionGoal: "Scheduled family practice appointment",
    aiPrompt: "Assist family medicine scheduling and office FAQs. No diagnosis.",
    salesStrategy: "New vs returning → book → preferred provider.",
    popularServices: ["Annual physical", "Sick visit", "Referrals"],
  }),
  defineIndustry({
    id: "dental-clinic",
    category: "healthcare",
    industryName: "Dental Clinic",
    catalogBlurb: "General dentistry booking with insurance and emergency paths.",
    designPersonality: "Bright · reassuring · smile-forward",
    colors: c("#0e7490", "#06b6d4", "#155e75", "#ecfeff", "#164e63"),
    assistantName: "Dr. Smile",
    assistantRole: "Your Dental Care Assistant",
    greeting: "Hi! Looking for a cleaning, checkup, or emergency dental help? Choose an option below.",
    matchKeywords: ["dental", "dentist", "dental clinic", "teeth cleaning"],
    primaryCta: { label: "Book Appointment", action: "book" },
    secondaryCta: { label: "Emergency Help", action: "emergency" },
    bubbleCta: "Need dental care?",
    footer: "Severe dental pain? Call the office or ER if needed.",
    businessGoal: "Fill hygiene and consult chairs",
    conversionGoal: "Booked dental appointment",
    aiPrompt: "Represent a dental clinic. No clinical diagnosis.",
    salesStrategy: "Need → urgency → insurance → book.",
    popularServices: ["Cleaning", "Fillings", "Whitening consult"],
    quickActions: qa([
      ["book", "Book Appointment", "calendar"],
      ["emergency", "Emergency Help", "alert"],
      ["services", "Our Services", "stethoscope"],
      ["checkup", "Dental Checkup", "heart"],
      ["insurance", "Insurance", "shield"],
      ["reviews", "Patient Reviews", "sparkles"],
      ["callback", "Call Me Back", "phone"],
      ["human", "Talk to Doctor", "headphones", "transfer_agent"],
    ]),
  }),
  defineIndustry({
    id: "orthodontics",
    category: "healthcare",
    industryName: "Orthodontics",
    catalogBlurb: "Braces and aligner consult funnel.",
    designPersonality: "Modern · aspirational",
    colors: c("#7c3aed", "#a78bfa", "#5b21b6", "#f5f3ff", "#2e1065"),
    assistantName: "Align Advisor",
    assistantRole: "Orthodontic consult specialist",
    greeting: "Curious about braces or clear aligners? I can help start a free consult.",
    matchKeywords: ["orthodont", "braces", "invisalign", "aligners"],
    primaryCta: { label: "Free Smile Consult", action: "consult" },
    secondaryCta: { label: "Before / After", action: "portfolio" },
    bubbleCta: "Straighten smile?",
    footer: "Results vary. Consult required.",
    businessGoal: "Book orthodontic consults",
    conversionGoal: "Consult scheduled",
    aiPrompt: "Help orthodontic consult bookings. No treatment guarantees.",
    salesStrategy: "Teen vs adult → aligners vs braces → consult.",
    popularServices: ["Clear aligners", "Braces", "Retainers"],
  }),
  defineIndustry({
    id: "eye-clinic",
    category: "healthcare",
    industryName: "Eye Clinic / Ophthalmology",
    catalogBlurb: "Vision exams, contacts, and specialty eye care.",
    designPersonality: "Clear · precise · optical",
    colors: c("#0284c7", "#38bdf8", "#075985", "#f0f9ff", "#0c4a6e"),
    assistantName: "Vision Desk",
    assistantRole: "Eye clinic assistant",
    greeting: "Need an eye exam, contacts, or specialty care? I can help you book.",
    matchKeywords: ["eye clinic", "optometr", "ophthalm", "vision center", "eye doctor"],
    primaryCta: { label: "Book Eye Exam", action: "book" },
    secondaryCta: { label: "Our Services", action: "services" },
    bubbleCta: "Book eye care",
    footer: "Sudden vision loss? Seek emergency care.",
    businessGoal: "Increase exam bookings",
    conversionGoal: "Scheduled eye exam",
    aiPrompt: "Assist eye clinic scheduling and FAQs. No diagnosis.",
    salesStrategy: "Exam vs specialty → insurance → book.",
    popularServices: ["Comprehensive exam", "Contacts", "Cataract consult"],
  }),
  defineIndustry({
    id: "diagnostic-lab",
    category: "healthcare",
    industryName: "Diagnostic & Laboratory",
    catalogBlurb: "Lab testing, walk-ins, and results guidance.",
    designPersonality: "Precise · efficient · clinical",
    colors: c("#4338ca", "#818cf8", "#312e81", "#eef2ff", "#1e1b4b"),
    assistantName: "Lab Concierge",
    assistantRole: "Diagnostics scheduling assistant",
    greeting: "Need lab work or imaging? I can help with scheduling, prep, and locations.",
    matchKeywords: ["diagnostic", "laboratory", "lab test", "blood test", "imaging center"],
    primaryCta: { label: "Schedule Test", action: "book" },
    secondaryCta: { label: "Prep Instructions", action: "prep" },
    bubbleCta: "Book lab work",
    footer: "Results interpretation requires your clinician.",
    businessGoal: "Increase scheduled tests",
    conversionGoal: "Booked lab / diagnostic appointment",
    aiPrompt: "Help schedule labs and share prep. No result interpretation.",
    salesStrategy: "Test type → fasting/prep → book location.",
    popularServices: ["Blood work", "Imaging", "Walk-in labs"],
  }),
  defineIndustry({
    id: "physical-therapy",
    category: "healthcare",
    industryName: "Physical Therapy",
    catalogBlurb: "PT evaluation booking and recovery support.",
    designPersonality: "Energetic · recovery-focused",
    colors: c("#ea580c", "#fb923c", "#9a3412", "#fff7ed", "#7c2d12"),
    assistantName: "PT Coach Desk",
    assistantRole: "Physical therapy assistant",
    greeting: "Recovering from an injury or surgery? I can help book a PT evaluation.",
    matchKeywords: ["physical therapy", "physiotherapy", "pt clinic", "rehab"],
    primaryCta: { label: "Book PT Eval", action: "book" },
    secondaryCta: { label: "Our Programs", action: "services" },
    bubbleCta: "Start PT",
    footer: "This chat is not a substitute for clinical evaluation.",
    businessGoal: "Fill eval slots",
    conversionGoal: "PT evaluation booked",
    aiPrompt: "Help book PT evaluations and explain programs. No diagnosis.",
    salesStrategy: "Injury/goal → referral status → book eval.",
    popularServices: ["Sports rehab", "Post-op PT", "Pain management"],
  }),
  defineIndustry({
    id: "mental-health",
    category: "healthcare",
    industryName: "Mental Health Clinic",
    catalogBlurb: "Therapy and psychiatry intake with careful tone.",
    designPersonality: "Calm · confidential · compassionate",
    colors: c("#5b21b6", "#8b5cf6", "#4c1d95", "#f5f3ff", "#2e1065"),
    assistantName: "Care Companion",
    assistantRole: "Mental health intake assistant",
    greeting: "You're in a safe place to ask about therapy, psychiatry, or how to get started.",
    matchKeywords: ["mental health", "therapy", "psychiatrist", "counseling", "behavioral health"],
    primaryCta: { label: "Request Intake", action: "intake" },
    secondaryCta: { label: "Our Services", action: "services" },
    bubbleCta: "Talk with us",
    footer: "If you are in crisis, call local emergency services or a crisis line.",
    businessGoal: "Increase qualified intakes",
    conversionGoal: "Intake request submitted",
    aiPrompt: "Support mental health intake. Crisis → emergency resources. No therapy in chat.",
    salesStrategy: "Need → modality → insurance → intake.",
    popularServices: ["Individual therapy", "Psychiatry", "Telehealth"],
  }),
  defineIndustry({
    id: "womens-health",
    category: "healthcare",
    industryName: "Women's Health / OB-GYN",
    catalogBlurb: "OB-GYN scheduling for wellness, prenatal, and specialty care.",
    designPersonality: "Supportive · private · expert",
    colors: c("#db2777", "#f472b6", "#9d174d", "#fdf2f8", "#831843"),
    assistantName: "Women's Care Desk",
    assistantRole: "OB-GYN clinic assistant",
    greeting: "I can help with OB-GYN appointments, prenatal visits, and common clinic questions.",
    matchKeywords: ["women's health", "obgyn", "ob-gyn", "gynecolog", "prenatal", "maternity"],
    primaryCta: { label: "Book Appointment", action: "book" },
    secondaryCta: { label: "Prenatal Care", action: "prenatal" },
    bubbleCta: "Women's health",
    footer: "Urgent pregnancy concerns may need emergency care.",
    businessGoal: "Grow wellness and prenatal bookings",
    conversionGoal: "OB-GYN appointment booked",
    aiPrompt: "Assist OB-GYN scheduling and FAQs. No medical diagnosis.",
    salesStrategy: "Visit type → new/returning → book.",
    popularServices: ["Annual exam", "Prenatal", "Family planning"],
  }),
];
