import { defineIndustry, qa } from "./factory";
import type { CepIndustryPreset, ColorPalette } from "./types";

function c(
  primary: string,
  primaryEnd: string,
  header: string,
  background: string,
  text: string,
): ColorPalette {
  return {
    primary,
    primaryEnd,
    header,
    background,
    text,
    accent: "#f59e0b",
    success: "#16a34a",
    warning: "#d97706",
    surface: "#ffffff",
    darkBackground: "#0f172a",
    darkText: "#f8fafc",
    darkHeader: header,
  };
}

export const HOME_SERVICES_PRESETS: CepIndustryPreset[] = [
  defineIndustry({
    id: "roofing",
    category: "home_services",
    industryName: "Roofing Company",
    catalogBlurb: "Roof inspection and estimate-led sales.",
    designPersonality: "Rugged · trustworthy · storm-ready",
    colors: c("#b45309", "#f59e0b", "#92400e", "#fffbeb", "#78350f"),
    assistantName: "Roof Desk",
    assistantRole: "Roofing estimate coordinator",
    greeting: "Storm damage or a new roof? I can help schedule a free inspection and estimate.",
    matchKeywords: ["roofing", "roof repair", "roof replacement", "roofer"],
    primaryCta: { label: "Free Roof Estimate", action: "estimate" },
    secondaryCta: { label: "Emergency Leak", action: "emergency" },
    bubbleCta: "Roof problems?",
    footer: "Licensed & insured roofing pros",
    businessGoal: "Book inspections that convert to jobs",
    conversionGoal: "Estimate / inspection scheduled",
    aiPrompt: "Qualify roofing jobs and book estimates. Capture ZIP and urgency.",
    salesStrategy: "Repair vs replace → storm/insurance → estimate.",
    popularServices: ["Replacement", "Repair", "Inspection"],
  }),
  defineIndustry({
    id: "hvac",
    category: "home_services",
    industryName: "HVAC Company",
    catalogBlurb: "AC/heat service, installs, and maintenance plans.",
    designPersonality: "Reliable · seasonal · service-first",
    colors: c("#0369a1", "#38bdf8", "#0c4a6e", "#f0f9ff", "#0c4a6e"),
    assistantName: "HVAC Desk",
    assistantRole: "HVAC service coordinator",
    greeting: "AC or heat issues? I can help book service, installs, or a maintenance plan.",
    matchKeywords: ["hvac", "air conditioning", "furnace", "ac repair", "heating cooling"],
    primaryCta: { label: "Book HVAC Service", action: "book" },
    secondaryCta: { label: "Free Estimate", action: "estimate" },
    bubbleCta: "HVAC help",
    footer: "Same-day options when available",
    businessGoal: "Fill service calendar + install pipeline",
    conversionGoal: "Service or estimate booked",
    aiPrompt: "Coordinate HVAC service and install estimates.",
    salesStrategy: "Repair vs install → urgency → book.",
    popularServices: ["AC repair", "Furnace", "Maintenance plans"],
  }),
  defineIndustry({
    id: "plumbing",
    category: "home_services",
    industryName: "Plumbing Service",
    catalogBlurb: "Emergency and scheduled plumbing dispatch.",
    designPersonality: "Fast · practical · emergency-ready",
    colors: c("#1d4ed8", "#60a5fa", "#1e3a8a", "#eff6ff", "#1e3a8a"),
    assistantName: "Plumbing Desk",
    assistantRole: "Plumbing dispatch assistant",
    greeting: "Leak, clog, or water heater issue? I can help get a plumber scheduled fast.",
    matchKeywords: ["plumber", "plumbing", "drain cleaning", "water heater", "leak repair"],
    primaryCta: { label: "Book Plumber", action: "book" },
    secondaryCta: { label: "Emergency Leak", action: "emergency" },
    bubbleCta: "Need a plumber?",
    footer: "Emergency dispatch when available",
    businessGoal: "Increase dispatched jobs",
    conversionGoal: "Plumbing visit booked",
    aiPrompt: "Dispatch plumbing jobs. Capture urgency and ZIP.",
    salesStrategy: "Emergency vs scheduled → ZIP → book.",
    popularServices: ["Drain cleaning", "Leak repair", "Water heaters"],
  }),
  defineIndustry({
    id: "electrician",
    category: "home_services",
    industryName: "Electrician",
    catalogBlurb: "Electrical service, panels, and install estimates.",
    designPersonality: "Safety-first · precise · licensed",
    colors: c("#ca8a04", "#facc15", "#a16207", "#fefce8", "#713f12"),
    assistantName: "Electric Desk",
    assistantRole: "Electrical service coordinator",
    greeting: "Need an electrician for repairs, panels, or installs? I can help schedule service.",
    matchKeywords: ["electrician", "electrical repair", "panel upgrade", "wiring"],
    primaryCta: { label: "Book Electrician", action: "book" },
    secondaryCta: { label: "Get Estimate", action: "estimate" },
    bubbleCta: "Electrical help",
    footer: "Licensed electricians · safety first",
    businessGoal: "Book electrical service & upgrades",
    conversionGoal: "Service / estimate scheduled",
    aiPrompt: "Coordinate electrical service requests. Safety first.",
    salesStrategy: "Issue type → safety check → book.",
    popularServices: ["Outlets", "Panel upgrade", "EV charger"],
  }),
  defineIndustry({
    id: "pest-control",
    category: "home_services",
    industryName: "Pest Control",
    catalogBlurb: "Inspection and recurring pest treatment plans.",
    designPersonality: "Clean · reassuring · proactive",
    colors: c("#15803d", "#4ade80", "#166534", "#f0fdf4", "#14532d"),
    assistantName: "Pest Desk",
    assistantRole: "Pest control coordinator",
    greeting: "Dealing with pests? I can help schedule an inspection or recurring protection plan.",
    matchKeywords: ["pest control", "exterminator", "termite", "rodent control"],
    primaryCta: { label: "Book Inspection", action: "book" },
    secondaryCta: { label: "Treatment Plans", action: "pricing" },
    bubbleCta: "Pest problems?",
    footer: "Family & pet-conscious treatment options",
    businessGoal: "Convert inspections to recurring plans",
    conversionGoal: "Inspection booked",
    aiPrompt: "Qualify pest issues and book inspections.",
    salesStrategy: "Pest type → home/business → inspection.",
    popularServices: ["General pest", "Termites", "Mosquito"],
  }),
  defineIndustry({
    id: "cleaning-service",
    category: "home_services",
    industryName: "Cleaning Service",
    catalogBlurb: "Home and office cleaning quotes and booking.",
    designPersonality: "Fresh · dependable · detail-oriented",
    colors: c("#0d9488", "#2dd4bf", "#0f766e", "#f0fdfa", "#134e4a"),
    assistantName: "Clean Desk",
    assistantRole: "Cleaning service coordinator",
    greeting: "Need home or office cleaning? I can help with one-time deep cleans or recurring plans.",
    matchKeywords: ["cleaning service", "house cleaning", "maid service", "office cleaning"],
    primaryCta: { label: "Get Cleaning Quote", action: "quote" },
    secondaryCta: { label: "Book Cleaning", action: "book" },
    bubbleCta: "Book cleaning",
    footer: "Background-checked cleaning pros",
    businessGoal: "Grow recurring cleaning clients",
    conversionGoal: "Quote or booking completed",
    aiPrompt: "Qualify cleaning jobs by size/frequency and quote.",
    salesStrategy: "Home vs office → frequency → quote/book.",
    popularServices: ["Recurring clean", "Deep clean", "Move-out"],
  }),
  defineIndustry({
    id: "landscaping",
    category: "home_services",
    industryName: "Landscaping",
    catalogBlurb: "Lawn, design, and outdoor maintenance estimates.",
    designPersonality: "Outdoor · seasonal · design-capable",
    colors: c("#166534", "#22c55e", "#14532d", "#f0fdf4", "#14532d"),
    assistantName: "Landscape Desk",
    assistantRole: "Landscaping coordinator",
    greeting: "Lawn care or landscape design? I can help request an estimate and share service options.",
    matchKeywords: ["landscaping", "lawn care", "lawn service", "hardscape", "garden design"],
    primaryCta: { label: "Free Estimate", action: "estimate" },
    secondaryCta: { label: "Our Services", action: "services" },
    bubbleCta: "Yard help",
    footer: "Seasonal maintenance & design builds",
    businessGoal: "Book estimates for maintenance and installs",
    conversionGoal: "Estimate requested",
    aiPrompt: "Qualify landscaping needs and book estimates.",
    salesStrategy: "Maintenance vs project → property size → estimate.",
    popularServices: ["Lawn care", "Mulch / beds", "Hardscape"],
  }),
  defineIndustry({
    id: "garage-door",
    category: "home_services",
    industryName: "Garage Door Repair",
    catalogBlurb: "Same-day garage door repair and opener service.",
    designPersonality: "Urgent · practical · fix-it energy",
    colors: c("#334155", "#64748b", "#0f172a", "#f8fafc", "#0f172a"),
    assistantName: "Garage Door Desk",
    assistantRole: "Garage door service coordinator",
    greeting: "Garage door stuck or opener failing? I can help schedule repair or a free estimate.",
    matchKeywords: ["garage door", "garage door repair", "garage door opener"],
    primaryCta: { label: "Book Repair", action: "book" },
    secondaryCta: { label: "New Door Estimate", action: "estimate" },
    bubbleCta: "Garage door help",
    footer: "Same-day repair when available",
    businessGoal: "Dispatch repairs + sell replacements",
    conversionGoal: "Repair booked or estimate set",
    aiPrompt: "Dispatch garage door repairs and estimates.",
    salesStrategy: "Repair vs replace → urgency → book.",
    popularServices: ["Spring repair", "Opener", "New doors"],
    quickActions: qa([
      ["repair", "Book Repair", "calendar"],
      ["emergency", "Door Won't Open", "alert"],
      ["estimate", "New Door Estimate", "calculator"],
      ["opener", "Opener Issues", "layers"],
      ["photos", "Send a Photo", "image"],
      ["financing", "Financing", "briefcase"],
      ["callback", "Call Me Back", "phone"],
      ["human", "Talk to Dispatcher", "headphones", "transfer_agent"],
    ]),
  }),
];
