import { defineIndustry, qa } from "./factory";
import type { CepIndustryPreset, ColorPalette } from "./types";

function c(
  primary: string,
  primaryEnd: string,
  header: string,
  background: string,
  text: string,
): ColorPalette {
  return {
    primary,
    primaryEnd,
    header,
    background,
    text,
    accent: "#f59e0b",
    success: "#16a34a",
    warning: "#d97706",
    surface: "#ffffff",
    darkBackground: "#0f172a",
    darkText: "#f8fafc",
    darkHeader: header,
  };
}

export const PROFESSIONAL_PRESETS: CepIndustryPreset[] = [
  defineIndustry({
    id: "law-firm",
    category: "professional",
    industryName: "Law Firm",
    catalogBlurb: "Intake for consults with careful compliance tone.",
    designPersonality: "Authoritative · discreet · precise",
    colors: c("#1e3a8a", "#3b82f6", "#172554", "#eff6ff", "#1e3a8a"),
    assistantName: "Legal Intake",
    assistantRole: "Law firm intake assistant",
    greeting: "I can help you request a consultation and share practice areas. This chat is not legal advice.",
    matchKeywords: ["law firm", "attorney", "lawyer", "legal services", "litigation"],
    primaryCta: { label: "Request Consultation", action: "consult" },
    secondaryCta: { label: "Practice Areas", action: "services" },
    bubbleCta: "Talk to our firm",
    footer: "Not legal advice · confidential intake",
    businessGoal: "Increase qualified consult intakes",
    conversionGoal: "Consultation request submitted",
    aiPrompt: "Law firm intake only. Never give legal advice. Capture matter type carefully.",
    salesStrategy: "Matter type → urgency → conflict check ask → consult.",
    popularServices: ["Consults", "Practice areas", "Case evaluation"],
  }),
  defineIndustry({
    id: "cpa-accounting",
    category: "professional",
    industryName: "CPA / Accounting Firm",
    catalogBlurb: "Tax and accounting client intake.",
    designPersonality: "Exact · calm · seasonal-smart",
    colors: c("#0f766e", "#14b8a6", "#115e59", "#f0fdfa", "#134e4a"),
    assistantName: "Accounting Desk",
    assistantRole: "CPA firm assistant",
    greeting: "Need tax help, bookkeeping, or a CPA consult? I can help you get started.",
    matchKeywords: ["cpa", "accounting firm", "tax accountant", "bookkeeping", "tax preparation"],
    primaryCta: { label: "Book CPA Consult", action: "consult" },
    secondaryCta: { label: "Our Services", action: "services" },
    bubbleCta: "Accounting help",
    footer: "Not tax advice until engaged",
    businessGoal: "Fill consult and tax-season capacity",
    conversionGoal: "CPA consult booked",
    aiPrompt: "Qualify accounting/tax intakes. No definitive tax advice in chat.",
    salesStrategy: "Individual vs business → service → consult.",
    popularServices: ["Tax prep", "Bookkeeping", "CFO advisory"],
  }),
  defineIndustry({
    id: "insurance-agency",
    category: "professional",
    industryName: "Insurance Agency",
    catalogBlurb: "Quote requests for personal and commercial coverage.",
    designPersonality: "Protective · clear · comparison-friendly",
    colors: c("#1d4ed8", "#60a5fa", "#1e40af", "#eff6ff", "#1e3a8a"),
    assistantName: "Insurance Desk",
    assistantRole: "Insurance quote assistant",
    greeting: "Looking for coverage? I can help start a quote for auto, home, life, or business insurance.",
    matchKeywords: ["insurance agency", "insurance agent", "auto insurance", "home insurance", "commercial insurance"],
    primaryCta: { label: "Get a Quote", action: "quote" },
    secondaryCta: { label: "Coverage Types", action: "services" },
    bubbleCta: "Get insured",
    footer: "Quotes subject to underwriting",
    businessGoal: "Increase quote starts",
    conversionGoal: "Insurance quote started",
    aiPrompt: "Start insurance quotes. No binding coverage promises.",
    salesStrategy: "Personal vs commercial → type → quote.",
    popularServices: ["Auto", "Home", "Business"],
  }),
  defineIndustry({
    id: "real-estate",
    category: "professional",
    industryName: "Real Estate Agency",
    catalogBlurb: "Buyer/seller lead capture and tour booking.",
    designPersonality: "Aspirational · local · deal-moving",
    colors: c("#166534", "#22c55e", "#14532d", "#f0fdf4", "#14532d"),
    assistantName: "Property Expert",
    assistantRole: "Real estate assistant",
    greeting: "Buying or selling? I can help search properties, book a viewing, or connect you with an agent.",
    matchKeywords: ["real estate", "realtor", "homes for sale", "property listing", "buy a home"],
    primaryCta: { label: "Book a Viewing", action: "book" },
    secondaryCta: { label: "Search Properties", action: "search" },
    bubbleCta: "Find a home",
    footer: "Local market experts",
    businessGoal: "Capture buyer/seller leads",
    conversionGoal: "Viewing booked or seller lead",
    aiPrompt: "Help real estate leads: buy, sell, tour booking.",
    salesStrategy: "Buy vs sell → area/budget → viewing/valuation.",
    popularServices: ["Buyer representation", "Listing", "Valuation"],
    quickActions: qa([
      ["search", "Search Properties", "map-pin"],
      ["viewing", "Book a Viewing", "calendar"],
      ["sell", "Sell Your Property", "briefcase"],
      ["value", "Property Valuation", "calculator"],
      ["services", "Our Services", "layers"],
      ["reviews", "Client Reviews", "sparkles"],
      ["callback", "Call Me Back", "phone"],
      ["human", "Talk to Agent", "headphones", "transfer_agent"],
    ]),
  }),
  defineIndustry({
    id: "mortgage",
    category: "professional",
    industryName: "Mortgage Company",
    catalogBlurb: "Pre-approval and mortgage consult intake.",
    designPersonality: "Confident · numbers-clear · guided",
    colors: c("#0e7490", "#22d3ee", "#155e75", "#ecfeff", "#164e63"),
    assistantName: "Mortgage Desk",
    assistantRole: "Mortgage consultant assistant",
    greeting: "Ready to explore a mortgage or pre-approval? I can help start the conversation.",
    matchKeywords: ["mortgage", "home loan", "pre-approval", "refinance", "mortgage broker"],
    primaryCta: { label: "Start Pre-Approval", action: "intake" },
    secondaryCta: { label: "Talk to Loan Officer", action: "call" },
    bubbleCta: "Home financing",
    footer: "Not a loan commitment · terms vary",
    businessGoal: "Increase pre-approval starts",
    conversionGoal: "Mortgage intake started",
    aiPrompt: "Qualify mortgage interest. No rate guarantees.",
    salesStrategy: "Purchase vs refi → timeline → intake.",
    popularServices: ["Purchase", "Refinance", "Pre-approval"],
  }),
  defineIndustry({
    id: "property-management",
    category: "professional",
    industryName: "Property Management",
    catalogBlurb: "Owner and tenant routing for managed properties.",
    designPersonality: "Operational · clear · responsive",
    colors: c("#334155", "#64748b", "#0f172a", "#f8fafc", "#0f172a"),
    assistantName: "Property Desk",
    assistantRole: "Property management assistant",
    greeting: "Owner or tenant? I can help with leasing, maintenance requests, and management inquiries.",
    matchKeywords: ["property management", "rental management", "apartment management", "tenant portal"],
    primaryCta: { label: "Owner Inquiry", action: "owner" },
    secondaryCta: { label: "Maintenance Request", action: "maintenance" },
    bubbleCta: "Property help",
    footer: "Owners & tenants supported",
    businessGoal: "Win owner contracts + handle tenant ops",
    conversionGoal: "Owner lead or maintenance ticket",
    aiPrompt: "Route owner vs tenant intents correctly.",
    salesStrategy: "Owner vs tenant → intent → form/handoff.",
    popularServices: ["Owner management", "Leasing", "Maintenance"],
  }),
  defineIndustry({
    id: "financial-advisor",
    category: "professional",
    industryName: "Financial Advisor",
    catalogBlurb: "Wealth planning consult booking.",
    designPersonality: "Trusted · calm · long-term",
    colors: c("#1e40af", "#3b82f6", "#1e3a8a", "#eff6ff", "#1e3a8a"),
    assistantName: "Advisor Desk",
    assistantRole: "Financial advisor assistant",
    greeting: "Exploring financial planning or investment guidance? I can help book an introductory meeting.",
    matchKeywords: ["financial advisor", "wealth management", "financial planner", "investment advisor"],
    primaryCta: { label: "Book Intro Meeting", action: "consult" },
    secondaryCta: { label: "Our Approach", action: "services" },
    bubbleCta: "Plan your future",
    footer: "Not personalized investment advice in chat",
    businessGoal: "Book qualified intro meetings",
    conversionGoal: "Advisor meeting booked",
    aiPrompt: "Book financial advisor intros. No personalized investment advice.",
    salesStrategy: "Goal → life stage → meeting.",
    popularServices: ["Retirement", "Investments", "Planning"],
  }),
  defineIndustry({
    id: "business-consultant",
    category: "professional",
    industryName: "Business Consultant",
    catalogBlurb: "Strategy and operations consulting intake.",
    designPersonality: "Sharp · diagnostic · executive",
    colors: c("#7c3aed", "#a78bfa", "#5b21b6", "#f5f3ff", "#2e1065"),
    assistantName: "Consulting Desk",
    assistantRole: "Business consulting assistant",
    greeting: "Need help growing or fixing operations? I can help scope a consulting discovery call.",
    matchKeywords: ["business consultant", "management consulting", "business coaching", "strategy consultant"],
    primaryCta: { label: "Book Discovery Call", action: "call" },
    secondaryCta: { label: "How We Help", action: "services" },
    bubbleCta: "Grow smarter",
    footer: "Custom engagements · clear scopes",
    businessGoal: "Win discovery calls",
    conversionGoal: "Discovery call booked",
    aiPrompt: "Qualify consulting opportunities and book discovery.",
    salesStrategy: "Problem → company size → discovery.",
    popularServices: ["Strategy", "Ops", "Go-to-market"],
  }),
  defineIndustry({
    id: "it-support",
    category: "professional",
    industryName: "IT Support / Managed IT Services",
    catalogBlurb: "MSP intake for support and managed services.",
    designPersonality: "Technical · calm · SLA-minded",
    colors: c("#0f172a", "#334155", "#020617", "#f8fafc", "#0f172a"),
    assistantName: "IT Desk",
    assistantRole: "Managed IT assistant",
    greeting: "IT issues or looking for managed services? I can help open a ticket or book a discovery call.",
    matchKeywords: ["managed it", "it support", "msp", "help desk", "managed services"],
    primaryCta: { label: "Open Support Ticket", action: "ticket" },
    secondaryCta: { label: "MSP Discovery Call", action: "call" },
    bubbleCta: "IT help",
    footer: "Business IT support & managed services",
    businessGoal: "Convert tickets + win MSP clients",
    conversionGoal: "Ticket opened or MSP call booked",
    aiPrompt: "Route IT support vs MSP sales correctly.",
    salesStrategy: "Break/fix vs managed → urgency → ticket/call.",
    popularServices: ["Help desk", "Security", "Cloud management"],
    quickActions: qa([
      ["ticket", "Open Support Ticket", "alert"],
      ["call", "MSP Discovery Call", "calendar"],
      ["services", "Managed Services", "layers"],
      ["security", "Cybersecurity", "shield"],
      ["remote", "Remote Support", "headphones"],
      ["pricing", "Plans & Pricing", "calculator"],
      ["callback", "Call Me Back", "phone"],
      ["human", "Talk to Engineer", "headphones", "transfer_agent"],
    ]),
  }),
];
