import { defineIndustry } from "./factory";
import type { CepIndustryPreset, ColorPalette } from "./types";

function c(
  primary: string,
  primaryEnd: string,
  header: string,
  background: string,
  text: string,
): ColorPalette {
  return {
    primary,
    primaryEnd,
    header,
    background,
    text,
    accent: "#f59e0b",
    success: "#16a34a",
    warning: "#d97706",
    surface: "#ffffff",
    darkBackground: "#0f172a",
    darkText: "#f8fafc",
    darkHeader: header,
  };
}

export const WEB_DIGITAL_PRESETS: CepIndustryPreset[] = [
  defineIndustry({
    id: "website-design",
    category: "web_digital",
    industryName: "Website Design Agency",
    catalogBlurb: "Website UX/UI design and redesign scoping.",
    designPersonality: "Product-polished · conversion-literate",
    colors: c("#0f766e", "#2dd4bf", "#115e59", "#f0fdfa", "#134e4a"),
    assistantName: "Web Desk",
    assistantRole: "Website design consultant",
    greeting: "Planning a new site or redesign? I can help scope pages, timeline, and packages.",
    matchKeywords: ["website design", "web design", "ui ux", "redesign website", "landing page design"],
    primaryCta: { label: "Scope My Website", action: "brief" },
    secondaryCta: { label: "See Site Designs", action: "portfolio" },
    bubbleCta: "Design my site",
    footer: "Design systems ready for modern builds",
    businessGoal: "Win website design projects",
    conversionGoal: "Discovery call or detailed brief",
    aiPrompt: "Qualify website design projects and book discovery.",
    salesStrategy: "New vs redesign → pages → CMS → discovery.",
    popularServices: ["Marketing sites", "Redesigns", "Landing pages"],
  }),
  defineIndustry({
    id: "wordpress-agency",
    category: "web_digital",
    industryName: "WordPress Agency",
    catalogBlurb: "WordPress builds, WooCommerce, and care plans.",
    designPersonality: "Practical · CMS-fluent · performance-minded",
    colors: c("#1d4ed8", "#60a5fa", "#1e40af", "#eff6ff", "#1e3a8a"),
    assistantName: "WP Concierge",
    assistantRole: "WordPress agency assistant",
    greeting: "Need a WordPress site, redesign, or care plan? I can help with packages and timelines.",
    matchKeywords: ["wordpress", "woocommerce", "wp agency", "elementor", "wordpress maintenance"],
    primaryCta: { label: "Get a WP Quote", action: "quote" },
    secondaryCta: { label: "Care Plans", action: "care" },
    bubbleCta: "WordPress help",
    footer: "Managed WordPress · security & updates available",
    businessGoal: "Grow WP builds and care retainers",
    conversionGoal: "Quote or care-plan interest",
    aiPrompt: "Qualify WordPress builds, Woo, migrations, retainers.",
    salesStrategy: "Build vs care vs migration → features → quote.",
    popularServices: ["WP builds", "WooCommerce", "Care plans"],
  }),
  defineIndustry({
    id: "seo-agency",
    category: "web_digital",
    industryName: "SEO Agency",
    catalogBlurb: "Organic growth with audit-led sales.",
    designPersonality: "Data-backed · ROI-spoken",
    colors: c("#047857", "#34d399", "#065f46", "#ecfdf5", "#064e3b"),
    assistantName: "SEO Scout",
    assistantRole: "SEO advisor",
    greeting: "Want more organic leads? I can outline SEO options and book a free visibility audit.",
    matchKeywords: ["seo agency", "search engine optimization", "organic traffic", "seo services"],
    primaryCta: { label: "Free SEO Audit", action: "audit" },
    secondaryCta: { label: "SEO Packages", action: "pricing" },
    bubbleCta: "Rank higher",
    footer: "SEO takes time — expectations set honestly",
    businessGoal: "Book SEO audits that convert to retainers",
    conversionGoal: "Audit booked",
    aiPrompt: "Book SEO audits. No fake ranking guarantees.",
    salesStrategy: "Goals → competitors → audit → retainer.",
    popularServices: ["Technical SEO", "Content SEO", "Link building"],
  }),
  defineIndustry({
    id: "local-seo-agency",
    category: "web_digital",
    industryName: "Local SEO Agency",
    catalogBlurb: "Map-pack and local organic growth.",
    designPersonality: "Local-dominant · map-fluent",
    colors: c("#0f766e", "#5eead4", "#115e59", "#f0fdfa", "#134e4a"),
    assistantName: "Local SEO Scout",
    assistantRole: "Local search advisor",
    greeting: "Want more map-pack leads? I can help with local SEO and a free local visibility check.",
    matchKeywords: ["local seo", "google maps ranking", "near me seo", "local pack"],
    primaryCta: { label: "Free Local Audit", action: "audit" },
    secondaryCta: { label: "Local Packages", action: "pricing" },
    bubbleCta: "Win the map pack",
    footer: "Local SEO compounds — no fake #1 promises",
    businessGoal: "Sell local SEO retainers",
    conversionGoal: "Local audit booked",
    aiPrompt: "Help local SEO audits and multi-location qualification.",
    salesStrategy: "Locations → competitors → audit → retainer.",
    popularServices: ["Map pack", "Citations", "Local content"],
  }),
  defineIndustry({
    id: "gbp-management",
    category: "web_digital",
    industryName: "Google Business Profile Management",
    catalogBlurb: "GBP optimization, posts, and review ops.",
    designPersonality: "Local-first · review-driven",
    colors: c("#c2410c", "#fb923c", "#9a3412", "#fff7ed", "#7c2d12"),
    assistantName: "Maps Manager",
    assistantRole: "Google Business Profile specialist",
    greeting: "Is your Google Business Profile winning the map pack? I can help with management plans and a free profile check.",
    matchKeywords: ["google business profile", "google my business", "gmb", "gbp", "maps listing"],
    primaryCta: { label: "Free GBP Check", action: "audit" },
    secondaryCta: { label: "Management Plans", action: "pricing" },
    bubbleCta: "Fix my GBP",
    footer: "We optimize listings — Google controls rankings",
    businessGoal: "Sell monthly GBP seats",
    conversionGoal: "GBP audit or plan inquiry",
    aiPrompt: "Qualify GBP management clients and book profile audits.",
    salesStrategy: "Locations → reviews → posts → plan.",
    popularServices: ["GBP optimization", "Reviews", "Posts / Q&A"],
  }),
  defineIndustry({
    id: "digital-marketing",
    category: "web_digital",
    industryName: "Digital Marketing Agency",
    catalogBlurb: "Full-funnel growth retainers.",
    designPersonality: "Growth-obsessed · KPI clear",
    colors: c("#db2777", "#f472b6", "#9d174d", "#fdf2f8", "#831843"),
    assistantName: "Growth Desk",
    assistantRole: "Digital marketing strategist assistant",
    greeting: "Looking for leads, not vanity metrics? I can map channels and book a growth strategy call.",
    matchKeywords: ["digital marketing", "marketing agency", "lead generation", "growth marketing"],
    primaryCta: { label: "Book Growth Call", action: "call" },
    secondaryCta: { label: "Channel Packages", action: "pricing" },
    bubbleCta: "Grow leads",
    footer: "Performance marketing with transparent reporting",
    businessGoal: "Close multi-channel retainers",
    conversionGoal: "Strategy call booked",
    aiPrompt: "Qualify digital marketing retainers. No guaranteed ROAS.",
    salesStrategy: "Goal → channels tried → budget → call.",
    popularServices: ["Paid + organic", "Lifecycle", "Creative testing"],
  }),
  defineIndustry({
    id: "social-media-marketing",
    category: "web_digital",
    industryName: "Social Media Marketing",
    catalogBlurb: "Content, community, and social ads management.",
    designPersonality: "On-brand · content-fluent · community-smart",
    colors: c("#4f46e5", "#818cf8", "#3730a3", "#eef2ff", "#1e1b4b"),
    assistantName: "Social Desk",
    assistantRole: "Social media marketing assistant",
    greeting: "Need consistent social content or paid social? I can outline packages and book a planning call.",
    matchKeywords: ["social media marketing", "instagram marketing", "facebook marketing", "social media agency"],
    primaryCta: { label: "Social Strategy Call", action: "call" },
    secondaryCta: { label: "Content Packages", action: "pricing" },
    bubbleCta: "Grow on social",
    footer: "Content + community + optional paid social",
    businessGoal: "Sell social retainers",
    conversionGoal: "Planning call booked",
    aiPrompt: "Qualify social media retainers and content needs.",
    salesStrategy: "Platforms → goals → package → call.",
    popularServices: ["Content calendar", "Community", "Social ads"],
  }),
  defineIndustry({
    id: "ppc-ads",
    category: "web_digital",
    industryName: "PPC / Google Ads Agency",
    catalogBlurb: "Paid search and performance ads management.",
    designPersonality: "Performance · accountable · test-driven",
    colors: c("#ea580c", "#fb923c", "#c2410c", "#fff7ed", "#7c2d12"),
    assistantName: "Ads Desk",
    assistantRole: "PPC / Google Ads specialist",
    greeting: "Want more qualified leads from Google Ads? I can review your account approach and book an ads strategy call.",
    matchKeywords: ["ppc", "google ads", "ppc agency", "paid search", "facebook ads", "meta ads"],
    primaryCta: { label: "Ads Strategy Call", action: "call" },
    secondaryCta: { label: "Audit My Ads", action: "audit" },
    bubbleCta: "Scale paid ads",
    footer: "No guaranteed ROAS — transparent testing & reporting",
    businessGoal: "Win PPC management retainers",
    conversionGoal: "Ads call or audit booked",
    aiPrompt: "Qualify PPC accounts. No guaranteed ROAS claims.",
    salesStrategy: "Budget → platforms → audit/call → retainer.",
    popularServices: ["Google Ads", "Meta Ads", "Landing CRO"],
  }),
];
